apiVersion: apps/v1
kind: Deployment
metadata:
  name: appmovies
spec:
  selector:
    matchLabels:
      app: appmovies
  template:
    metadata:
      labels:
        app: appmovies
    spec:
      containers:
        - name: appmovies
          image: brunomor7/rotten-potatoes:1.0
          ports:
            - containerPort: 7700
          env:
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: svc-mongo
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWORD
              value: pwd12340
               
---

apiVersion: v1
kind: Service
metadata:
  name: svc-app
spec:
  selector:
    app: appmovies
  ports:
  - port: 80
    targetPort: 7700
    nodePort: 30000
  type: NodePort